AWSTemplateFormatVersion: "2010-09-09"
Description: CF-NestedCWAlarms

Parameters:
  pEc2InstanceId:
    Type: AWS::EC2::Instance::Id
    Description: EC2 to monitor

Resources:
  
  NestedInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
      TimeoutInMinutes: 60

  Outputs:
    StackRef:
      Value: !Ref CF-NestedInstance
    NestedOutputs:
      Value: !GetAtt CF-NestedInstance.Outputs.InstanceID  
       
        # InstanceID:
        #   !ImportValue ${InstanceID}-NestedInstanceID
        
  rCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref pEc2InstanceId